### PR TITLE
Add Prettier Configuration

### PR DESCRIPTION
**Pull request by Cryst67**
Setup and configured Prettier for basic formatting and format on save.

### CODE REVIEW

**Comment by zachtsch** [comment]
Why?

**Comment by zachtsch** [comment]
Why do we want this?

**Comment by Cryst67** [comment]
Just some basic formatting rules and formatting on save so the codebase has consistent styling

**Comment by zachtsch** [comment]
Sounds reasonable.  Approved.

Can we talk about the arrowParens rule?

I don't mind

x => x + 1

**Comment by Cryst67** [comment]
`x => x + 1` works well, but we would have inconsistent styling for anonymous functions with no params 
Ex: `const exampleFunc = () => {};`
or `<Button onClick={() => {}}>Submit</Button>
So, having parentheses around all arrow functions might be better for consistent styling.

**Pull request merged**
